//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTrap.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTrap.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you entered is already in use..
        /// </summary>
        public static string email_duplicate {
            get {
                return ResourceManager.GetString("email_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute the operation. Try again later..
        /// </summary>
        public static string error_geral {
            get {
                return ResourceManager.GetString("error_geral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the user..
        /// </summary>
        public static string error_get_user {
            get {
                return ResourceManager.GetString("error_get_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. Try again later..
        /// </summary>
        public static string error_login {
            get {
                return ResourceManager.GetString("error_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not receive the position..
        /// </summary>
        public static string error_receive_position {
            get {
                return ResourceManager.GetString("error_receive_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the user. Try again later..
        /// </summary>
        public static string error_save_user {
            get {
                return ResourceManager.GetString("error_save_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate your user. Try again..
        /// </summary>
        public static string invalid_token {
            get {
                return ResourceManager.GetString("invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear Trap.
        /// </summary>
        public static string name_bear_trap {
            get {
                return ResourceManager.GetString("name_bear_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs Trap.
        /// </summary>
        public static string name_dogs_trap {
            get {
                return ResourceManager.GetString("name_dogs_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Trap.
        /// </summary>
        public static string name_loop_trap {
            get {
                return ResourceManager.GetString("name_loop_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Trap.
        /// </summary>
        public static string name_mine_trap {
            get {
                return ResourceManager.GetString("name_mine_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration has been successfully completed..
        /// </summary>
        public static string success_save_user {
            get {
                return ResourceManager.GetString("success_save_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to arm trap. Try again later..
        /// </summary>
        public static string trap_armed_error {
            get {
                return ResourceManager.GetString("trap_armed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid location to arm the trap..
        /// </summary>
        public static string trap_armed_location_invalid {
            get {
                return ResourceManager.GetString("trap_armed_location_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the trap in your inventory..
        /// </summary>
        public static string trap_armed_user_no_has {
            get {
                return ResourceManager.GetString("trap_armed_user_no_has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have traps in your inventory..
        /// </summary>
        public static string trap_armed_user_no_traps {
            get {
                return ResourceManager.GetString("trap_armed_user_no_traps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was caught in a trap!.
        /// </summary>
        public static string you_caught_user_trap {
            get {
                return ResourceManager.GetString("you_caught_user_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were caught in a trap!.
        /// </summary>
        public static string you_were_caught_trap {
            get {
                return ResourceManager.GetString("you_were_caught_trap", resourceCulture);
            }
        }
    }
}
